# Generated by Django 4.0.1 on 2022-07-20 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_profile_delete_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='password_reset_code',
            field=models.CharField(default='', max_length=6),
        ),
    ]
